// Generated by CoffeeScript 1.6.2
(function() {
  var EditBot, Twit, argv, cheerio, loadJson, main, minimist, request, wikichanges;

  Twit = require('twit');

  cheerio = require('cheerio');

  request = require('request');

  minimist = require('minimist');

  wikichanges = require('wikichanges');

  EditBot = (function() {
    function EditBot(config) {
      this.config = config;
      this.pages = {};
    }

    EditBot.prototype.run = function() {
      var wikipedia,
        _this = this;

      this._update(this.config.refresh);
      wikipedia = new wikichanges.WikiChanges({
        ircNickname: this.config.nick,
        wikipedias: ["#en.wikipedia"]
      });
      return wikipedia.listen(function(edit) {
        return _this.inspect(edit);
      });
    };

    EditBot.prototype.inspect = function(edit) {
      var status, twitter;

      console.log("inspecting " + edit.page);
      if (!this.pages[edit.page]) {

      } else if (edit.robot) {

      } else {
        status = this._getStatus(edit);
        console.log(status);
        twitter = new Twit(this.config);
        return twitter.post('statuses/update', {
          status: status
        }, function(err) {
          if (err) {
            return console.log(err);
          }
        });
      }
    };

    EditBot.prototype._getStatus = function(edit) {
      var status, statusLength, title, titleLength, user;

      title = edit.page;
      user = edit.anonymous ? "Anonymous" : edit.user;
      status = "" + title + " Wikipedia article edited by " + user + " ";
      statusLength = status.length + 22;
      if (statusLength > 140) {
        titleLength = title.length - (statusLength - 140);
        title = title.slice(0, +titleLength + 1 || 9e9);
      }
      return status = ("" + title + " Wikipedia article edited by " + user + " ") + edit.url;
    };

    EditBot.prototype._update = function(refresh) {
      var newPages,
        _this = this;

      newPages = [];
      return this._getPages(function(pages) {
        var doUpdate;

        _this.pages = pages;
        console.log("monitoring " + (Object.keys(_this.pages).length) + " pages");
        if (refresh instanceof Function) {
          return refresh();
        } else {
          doUpdate = function() {
            return _this._update(refresh);
          };
          return setTimeout(doUpdate, refresh * 1000);
        }
      });
    };

    EditBot.prototype._getPages = function(callback) {
      var pages;

      pages = {};
      return this._getDom(this.config.page, function($) {
        var a, _i, _len, _ref;

        _ref = $('a[href]');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          a = _ref[_i];
          if ($(a).attr('href').match(/^\/wiki\/(.+)$/)) {
            pages[$(a).attr('title')] = true;
          }
        }
        return callback(pages);
      });
    };

    EditBot.prototype._getDom = function(url, callback) {
      var _this = this;

      return request(url, function(err, response, body) {
        if (err) {
          console.log(err);
          return;
        }
        return callback(cheerio.load(body));
      });
    };

    return EditBot;

  })();

  loadJson = function(path) {
    if (path[0] !== '/' && path.slice(0, 2) !== './') {
      path = './' + path;
    }
    return require(path);
  };

  argv = minimist(process.argv.slice(2), {
    "default": {
      config: './config.json',
      list: false
    }
  });

  main = function() {
    var c, config;

    config = loadJson(argv.config);
    c = new EditBot(config);
    if (argv.list) {
      return c._update(function() {
        var page, _i, _len, _ref, _results;

        _ref = c.pages;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          page = _ref[_i];
          _results.push(console.log(page));
        }
        return _results;
      });
    } else {
      return c.run();
    }
  };

  if (require.main === module) {
    main();
  }

}).call(this);
